# Generated by Django 4.1.7 on 2023-04-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin_login',
            new_name='Admin',
        ),
    ]
