# Generated by Django 4.1.7 on 2023-04-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicationform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('contact_info', models.CharField(max_length=50)),
                ('work_experience', models.CharField(choices=[('0-1', 'Less than 1 year'), ('1-2', '1-2 years'), ('2-5', '2-5 years'), ('5-10', '5-10 years'), ('10+', 'More than 10 years')], max_length=10)),
                ('education', models.CharField(choices=[('high_school', 'High School'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], max_length=20)),
                ('skills', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('csharp', 'C#'), ('php', 'PHP'), ('ruby', 'Ruby'), ('other', 'Other')], max_length=20)),
                ('resume', models.FileField(upload_to='')),
            ],
        ),
    ]
