# Generated by Django 4.1.7 on 2023-04-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_jobapplicationform_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicationform',
            name='work_experience',
            field=models.CharField(choices=[('0-1', 'Less than 1 year'), ('1-2', '1-2 years'), ('2-5', '2-5 years'), ('5-10', '5-10 years'), ('10+', 'More than 10 years')], max_length=100),
        ),
    ]
